/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ClienteDAO;
import Entity.Cliente;
import Exceptions.CamposBrancosException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Outros.Util;
import Outros.ComboBox;
import java.awt.Color;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
//import Utils.ComboBoxData;
//import Utils.Util;
//import Utils.VerificadorDeEntradas;
//import java.util.Calendar;
//import java.util.GregorianCalendar;

/**
 *
 * @author Wagner Chaves
 */
public class NovoCliente extends javax.swing.JFrame {

    /**
     * Creates new form NovoCliente
     */
    private final Calendar cal;
    private final ComboBox cbd;

    public NovoCliente() {
        cbd = new ComboBox();
        cal = GregorianCalendar.getInstance();

        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalvar = new javax.swing.JButton();
        jLabelCadNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabelRG = new javax.swing.JLabel();
        tfRg = new javax.swing.JFormattedTextField();
        jLabelCPF = new javax.swing.JLabel();
        tfCpf = new javax.swing.JFormattedTextField();
        jLabelDataDeNasc = new javax.swing.JLabel();
        jLabel1CadastroDeCliente = new javax.swing.JLabel();
        jLabelLogradouro = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JTextField();
        jLabelCep = new javax.swing.JLabel();
        tfCep = new javax.swing.JFormattedTextField();
        jLabelBairro = new javax.swing.JLabel();
        tfBairro = new javax.swing.JTextField();
        jLabelCelular = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JFormattedTextField();
        jLabelLogradouro1 = new javax.swing.JLabel();
        tfCidade = new javax.swing.JTextField();
        jLabelUF = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox();
        jLabelCep1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfObs = new javax.swing.JTextArea();
        jLabelNomeInvld = new javax.swing.JLabel();
        jLabelNomeInvld2 = new javax.swing.JLabel();
        jLabelNomeInvld3 = new javax.swing.JLabel();
        jLabelNomeInvld4 = new javax.swing.JLabel();
        jcbDiaNascimento = new javax.swing.JComboBox();
        jcbMesNascimento = new javax.swing.JComboBox();
        jcbAnoNascimento = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalvar.setText("SALVAR");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 101, 32));

        jLabelCadNome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCadNome.setText("Nome:");
        getContentPane().add(jLabelCadNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 86, -1, -1));

        tfNome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        getContentPane().add(tfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 490, 25));

        jLabelRG.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelRG.setText("RG:");
        getContentPane().add(jLabelRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        try {
            tfRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfRg.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        getContentPane().add(tfRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 140, 25));

        jLabelCPF.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCPF.setText("CPF:");
        getContentPane().add(jLabelCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        try {
            tfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCpf.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCpfFocusLost(evt);
            }
        });
        getContentPane().add(tfCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 180, 25));

        jLabelDataDeNasc.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelDataDeNasc.setText("Data de Nasc:");
        getContentPane().add(jLabelDataDeNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 163, -1, -1));

        jLabel1CadastroDeCliente.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1CadastroDeCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1CadastroDeCliente.setText("CADASTRO DE CLIENTE");
        jLabel1CadastroDeCliente.setToolTipText("");
        jLabel1CadastroDeCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1CadastroDeCliente.setMaximumSize(new java.awt.Dimension(740, 80));
        jLabel1CadastroDeCliente.setMinimumSize(new java.awt.Dimension(740, 80));
        jLabel1CadastroDeCliente.setPreferredSize(new java.awt.Dimension(740, 70));
        jLabel1CadastroDeCliente.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1CadastroDeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 576, 80));

        jLabelLogradouro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelLogradouro.setText("Endereço:");
        getContentPane().add(jLabelLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 206, -1, -1));

        tfEndereco.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        getContentPane().add(tfEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 480, 25));

        jLabelCep.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCep.setText("CEP:");
        getContentPane().add(jLabelCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 285, -1, -1));

        try {
            tfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCep.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(tfCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 282, 140, 25));

        jLabelBairro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelBairro.setText("Bairro:");
        getContentPane().add(jLabelBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        tfBairro.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        getContentPane().add(tfBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 170, 25));

        jLabelCelular.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCelular.setText("Telefone:");
        getContentPane().add(jLabelCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 285, -1, -1));

        try {
            tfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfTelefone.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        getContentPane().add(tfTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 282, 130, -1));

        jLabelLogradouro1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelLogradouro1.setText("Cidade:");
        getContentPane().add(jLabelLogradouro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 242, -1, -1));

        tfCidade.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        getContentPane().add(tfCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 238, 240, 25));

        jLabelUF.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelUF.setText("UF:");
        getContentPane().add(jLabelUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 242, -1, -1));

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbEstado.setMinimumSize(new java.awt.Dimension(56, 33));
        cbEstado.setPreferredSize(new java.awt.Dimension(56, 33));
        getContentPane().add(cbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 239, 100, 25));

        jLabelCep1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCep1.setText("Observações:");
        getContentPane().add(jLabelCep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 325, -1, -1));

        tfObs.setColumns(20);
        tfObs.setRows(5);
        jScrollPane1.setViewportView(tfObs);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 347, 550, -1));

        jLabelNomeInvld.setForeground(new java.awt.Color(255, 0, 0));
        jLabelNomeInvld.setText("*");
        getContentPane().add(jLabelNomeInvld, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 26, -1));

        jLabelNomeInvld2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelNomeInvld2.setText("*");
        getContentPane().add(jLabelNomeInvld2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 26, -1));

        jLabelNomeInvld3.setForeground(new java.awt.Color(255, 0, 0));
        jLabelNomeInvld3.setText("*");
        getContentPane().add(jLabelNomeInvld3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        jLabelNomeInvld4.setForeground(new java.awt.Color(255, 0, 0));
        jLabelNomeInvld4.setText("*");
        getContentPane().add(jLabelNomeInvld4, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 287, 26, -1));

        jcbDiaNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDiaNascimentoActionPerformed(evt);
            }
        });
        getContentPane().add(jcbDiaNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));
        cbd.loadDayOfMonth(jcbDiaNascimento, 0, GregorianCalendar.getInstance().get(Calendar.YEAR));

        jcbMesNascimento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jcbMesNascimento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbMesNascimentoItemStateChanged(evt);
            }
        });
        getContentPane().add(jcbMesNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 98, -1));
        cbd.loadMonths(jcbMesNascimento);

        jcbAnoNascimento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbAnoNascimentoItemStateChanged(evt);
            }
        });
        getContentPane().add(jcbAnoNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));
        cbd.loadYears(jcbAnoNascimento, GregorianCalendar.getInstance().get(Calendar.YEAR));

        jButton1.setText("LIMPAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        if (ValidarCampos()) {
            if (JOptionPane.showConfirmDialog(null, "Deseja realmente inserir este funcionário", "Salvar", JOptionPane.YES_NO_OPTION) == 0) {
                Cliente cli;
                try {
                    String dataNasc = jcbAnoNascimento.getSelectedItem() + "-" + (int) (jcbMesNascimento.getSelectedIndex() + 1) + "-" + jcbDiaNascimento.getSelectedItem();
                    cli = new Cliente(tfNome.getText(), dataNasc, tfCpf.getText(), tfRg.getText(), tfTelefone.getText(), tfEndereco.getText(), tfBairro.getText(), tfCidade.getText(), tfCep.getText(), cbEstado.getSelectedItem() + "", tfObs.getText());
                    ClienteDAO cliDAO = new ClienteDAO();
                    if (cliDAO.inserir(cli)) {
                        JOptionPane.showMessageDialog(null, "Cadastro do cliente " + cli.getNome() + " realizado com sucesso");
                        ClearCampos();
                        tfNome.requestFocus();
                    }else{
                        JOptionPane.showMessageDialog(null, "CPF existente, o cliente já está cadastrado. ", "Erro de cadastro", JOptionPane.ERROR_MESSAGE);
                    }
                        
                } catch (CamposBrancosException ex) {
                    JOptionPane.showMessageDialog(null, ex.toString(), "Erro de cadastro", JOptionPane.ERROR_MESSAGE);
                    tfNome.requestFocus();
                    System.out.println(ex.getCause());
                }
                //dispose();                
            }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void tfCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCpfFocusLost

    }//GEN-LAST:event_tfCpfFocusLost

    private void jcbDiaNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDiaNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbDiaNascimentoActionPerformed

    private void jcbMesNascimentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbMesNascimentoItemStateChanged
        if (jcbAnoNascimento.getSelectedItem() != null) {
            cbd.loadDayOfMonth(jcbDiaNascimento, jcbMesNascimento.getSelectedIndex(), Integer.parseInt(jcbAnoNascimento.getSelectedItem().toString()));
        }
    }//GEN-LAST:event_jcbMesNascimentoItemStateChanged

    private void jcbAnoNascimentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbAnoNascimentoItemStateChanged
        if (jcbAnoNascimento.getSelectedItem() != null) {
            cbd.loadDayOfMonth(jcbDiaNascimento, jcbMesNascimento.getSelectedIndex(), Integer.parseInt(jcbAnoNascimento.getSelectedItem().toString()));
        }
    }//GEN-LAST:event_jcbAnoNascimentoItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ClearCampos();
        tfNome.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoCliente().setVisible(true);
            }
        });
    }

    private boolean ValidarCampos() {
        boolean Result = true;

        if (Util.validacpf(tfCpf.getText())) {
            tfCpf.setBackground(Color.green);
        } else {
            tfCpf.setBackground(Color.red);
            Util.dispayMsg("CPF inválido!");
            tfCpf.requestFocus();
            Result = false;

        }

        if (Result) {
            String dataNasc = jcbAnoNascimento.getSelectedItem() + "-" + (int) (jcbMesNascimento.getSelectedIndex() + 1) + "-" + jcbDiaNascimento.getSelectedItem();
            DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            try {
                Date date = (Date) formatter.parse(dataNasc);
                if (!Util.validarDataNasc(date)) {
                    Util.dispayMsg("Data de nascimento inválida!");
                    Result = false;
                }
            } catch (ParseException ex) {
                Result = false;
                Util.dispayMsg("Data de nascimento inválida!");
                Logger.getLogger(NovoCliente.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        return Result;
    }

    private void ClearCampos() {
        tfNome.setText(null);
        tfRg.setText(null);
        tfCpf.setText(null);
        jcbAnoNascimento.setSelectedIndex(0);
        jcbDiaNascimento.setSelectedIndex(0);
        jcbMesNascimento.setSelectedIndex(0);
        tfBairro.setText(null);
        tfEndereco.setText(null);
        tfCidade.setText(null);
        cbEstado.setSelectedIndex(0);
        tfCep.setText(null);
        tfTelefone.setText(null);
        tfObs.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1CadastroDeCliente;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCadNome;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelCep;
    private javax.swing.JLabel jLabelCep1;
    private javax.swing.JLabel jLabelDataDeNasc;
    private javax.swing.JLabel jLabelLogradouro;
    private javax.swing.JLabel jLabelLogradouro1;
    private javax.swing.JLabel jLabelNomeInvld;
    private javax.swing.JLabel jLabelNomeInvld2;
    private javax.swing.JLabel jLabelNomeInvld3;
    private javax.swing.JLabel jLabelNomeInvld4;
    private javax.swing.JLabel jLabelRG;
    private javax.swing.JLabel jLabelUF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcbAnoNascimento;
    private javax.swing.JComboBox jcbDiaNascimento;
    private javax.swing.JComboBox jcbMesNascimento;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JFormattedTextField tfCep;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JFormattedTextField tfCpf;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextArea tfObs;
    private javax.swing.JFormattedTextField tfRg;
    private javax.swing.JFormattedTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
}
